# ==================================================================================== #
# This is the Nmap Dockerfile. It builds a minimal Alpine-based container equipped     #
# with Nmap and its default scripting engine (NSE) files.                              #
# Running Nmap inside an ephemeral container keeps the host system perfectly clean     #
# and ensures cross-platform consistency without messy local installations.            #
# ==================================================================================== #

FROM alpine:latest
RUN apk add --no-cache nmap nmap-scripts
RUN addgroup -S -g 65532 scanner \
    && adduser -S -D -H -u 65532 -G scanner scanner
USER 65532:65532
ENTRYPOINT ["nmap"]
