# ==================================================================================================================================== #
# This is the Nuclei Dockerfile. It uses the official ProjectDiscovery image as a base                                                 #
# but forcefully updates the engine and bakes the latest vulnerability templates directly into the image layers.                       #
# This ensures our ephemeral containers can start blasting immediately without wasting time downloading templates on every run.        #
# ==================================================================================================================================== #

FROM projectdiscovery/nuclei:latest
RUN nuclei -update-templates
RUN nuclei -update
USER 65532:65532
ENTRYPOINT ["nuclei"]
